config/routes.rb
#
# Routes for FunnelCake rails engine
#
Rails.application.routes.draw do

  match 'analytics', :to => "Analytics::Dashboards#overview"

  namespace :analytics do
    resources :events
    
    resources :conversions do
      member do
        get :history
        get :visitors
      end
    end

    resources :states do
      member do
        get :visitors
      end
    end

    resources :ignores
    
    resources :visitors
    
    resources :stats
    
    resources :dashboards do
      collection do
        get :main
        get :cec
        get :diagram
        get :overview
        get :clear_cache
        get :customers
      end
    end
  end

end

app/models/analytics/event.rb
class Analytics::Event

  include Comparable
  def <=>(other)
    return 0 if created_at.nil? or other.created_at.nil?
    created_at <=> other.created_at
  end

end

app/models/analytics/ignore.rb
class Analytics::Ignore
end

app/models/analytics/visitor.rb
require 'funnel_cake/has_funnel/user_extensions'

module Analytics
  class Visitor
  include FunnelCake::HasFunnel::UserExtensions

  # Create a Analytics::Event, as a callback to a state_machine transition
  def log_transition(from, to, event, data, opts)
    update_statistics(data) if events.empty?  # if this is the first event, update the global statistics

    self.events << Analytics::Event.create({
      :from=>from.to_s, :to=>to.to_s,
      :url=>data[:url],
      :referer=>data[:referer],
      :user_agent=>data[:user_agent],
      :name=>event.to_s
    })
    self.save
  end

  # Utility method for logging funnel events from within application code
  # (This is probably how most funnel events will be triggered)
  # - First check if the event is legal... if not, log an error I guess!
  # - Second, send() the event method with the accompanying data
  def log_funnel_event(event, data={})
    unless self.valid_events.include?(event.to_sym)
      Rails.logger.info "#{self.class.to_s} couldn't log FunnelCake event: #{event} This event is not valid for state: #{self.current_state}, ip: #{self.ip}"
      return
    end
    self.send(event.to_s+"!", data)
  end

  end
end

app/controllers/analytics/common_controller.rb
class Analytics::CommonController < ApplicationController
  unloadable if RAILS_ENV=='development'

  before_filter :setup_funnel_cake_includes
  def setup_funnel_cake_includes
    @javascripts ||= []
    @stylesheets ||= []

    @javascripts.push 'excanvas'
    @javascripts.push 'funnelcake'
    @javascripts.push 'canviz'
    @javascripts.push 'path'
    @javascripts.push 'x11colors'
    @javascripts.push 'flotr.debug-0.2.0-alpha'
    @stylesheets.push 'funnel_cake'
  end

  helper 'analytics/common'
  include Analytics::CommonHelper

  private

  def add_filter_options(options)
    data = {}
    if params[:compare]
      compare = ActiveSupport::JSON.decode(params[:compare])
      data = {:compare=>compare.collect {|cur_filter_data| process_filter_data(cur_filter_data)}}
    end
    data = process_filter_data(ActiveSupport::JSON.decode(params[:filter_data])) if params[:filter_data]
    options.merge(data)
  end

  def process_filter_data(data)
    data = data.inject({}) do |h, (k, v)|
      v = convert_hash_values_to_regexes(v) if v.is_a?(Hash)
      h[k.to_sym] = v unless v.blank?
      h
    end
    data
  end

  def convert_hash_values_to_regexes(hash)
    hash.inject({}) do |h, (k,v)|
      h[k.to_sym] = v[/^\/.*\/$/].blank? ? v : /#{v[1..-2]}/ unless v.blank?
      h
    end
  end

  def grab_date_range
    if params[:time_period]
      return current_period(params[:time_period].to_i.days)
    elsif !params[:date_range_start].blank? and !params[:date_range_end].blank?
      return params[:date_range_start].to_date..params[:date_range_end].to_date
    end
    return 1.month.ago..0.days.ago
  end

end

app/controllers/analytics/conversions_controller.rb
class Analytics::ConversionsController < Analytics::CommonController
  include Analytics::ConversionsHelper

  before_filter :load_state_from_id, :only=>[:show, :history, :visitors]
  def load_state_from_id
    @start_state = params[:id].sub(/-.*/,'')
    @end_state = params[:id].sub(/[^-]*-/,'')
  end

  def index
    respond_to do |format|
      format.html # show.html.erb
    end
  end

  def compare
    respond_to do |format|
      format.html # show.html.erb
    end
  end

  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json do
        json = {}

        @date_range = grab_date_range
        @options = add_filter_options({:date_range=>@date_range, :attrition_period=>1.month})
        json[:stats] = FunnelCake.engine.conversion_stats(@start_state, @end_state, @options)

        if params[:show_previous_period]=='true'
          @previous_date_range = previous_date_range(@date_range, duration_of(@date_range)==30)
          @previous_options = add_filter_options({:date_range=>@previous_date_range, :attrition_period=>1.month})
          json[:previous_stats] = FunnelCake.engine.conversion_stats(@start_state, @end_state, @previous_options)
        end

        render :json=>json.to_json and return
      end
    end
  end

  def visitors
    @date_range = grab_date_range
    @options = add_filter_options({:date_range=>@date_range, :attrition_period=>1.month})
    respond_to do |format|
      format.html do
        render :partial=>'visitors',
                :locals=>{:start_state=>@start_state, :end_state=>@end_state, :options=>@options}
      end
    end
  end

  def history
    @time_period = params[:time_period].to_i.days
    @state = params[:id]
    stat = params[:stat].blank? ? :number : params[:stat].to_sym
    @options = add_filter_options({:time_period=>@time_period, :stat=>stat})
    respond_to do |format|
      format.json do
        render :json=>FunnelCake.engine.conversion_history(@start_state, @end_state, @options).to_json and return
      end
      format.csv do
        send_data(FunnelCake.engine.conversion_history(@start_state, @end_state, @options).values.first.to_csv,
              :type => 'text/csv; charset=utf-8; header=present',
              :filename => "#{@state}-#{params[:time_period]}day_history.csv") and return
      end
    end
  end

end

app/controllers/analytics/dashboards_controller.rb
class Analytics::DashboardsController < Analytics::CommonController

  helper 'analytics/stats'
  helper 'analytics/events'

  def diagram
    @date_range = grab_date_range
    @options = add_filter_options({:date_range=>@date_range, :attrition_period=>1.month})

    json = []
    Analytics::Visitor.event_table.each do |ev_name, ev|
      Analytics::Visitor.transition_table[ev_name].each do |trans|
        json << {
          :from => trans.from,
          :to => trans.to,
          :stats => FunnelCake.engine.move_stats(trans.from, trans.to, @options),
          :to_primary => Analytics::Visitor.states_table[trans.to].primary?
        }  unless Analytics::Visitor.states_table[trans.from].hidden? or Analytics::Visitor.states_table[trans.to].hidden?
      end
    end

    respond_to do |format|
      format.json { render :json=>json.to_json and return }
    end
  end

  def overview
  end

end

app/controllers/analytics/events_controller.rb
class Analytics::EventsController < Analytics::CommonController
  unloadable if RAILS_ENV=='development'

  helper 'analytics/stats'

  def index
    limit = params[:limit].nil? ? 25 : params[:limit]

    respond_to do |format|
      format.html do
        @events = Analytics::Visitor.all(:limit=>limit, :order=>'updated_at DESC')
        @events = @events.collect {|v| v.events}.flatten.delete_if {|e| e.nil? or e.created_at.nil?}.sort {|a,b| b.created_at <=> a.created_at }
      end
    end
  end

  # GET /events/1
  def show
    @event = Analytics::Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
    end
  end

end

app/controllers/analytics/ignores_controller.rb
class Analytics::IgnoresController < ApplicationController

  helper 'analytics/common'

  # GET /ignores
  # GET /ignores.xml
  def index
    @ignores = Analytics::Ignore.all

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /ignores/1
  # GET /ignores/1.xml
  def show
    @ignore = Analytics::Ignore.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  # GET /ignores/new
  # GET /ignores/new.xml
  def new
    @ignore = Analytics::Ignore.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /ignores/1/edit
  def edit
    @ignore = Analytics::Ignore.find(params[:id])
  end

  # POST /ignores
  # POST /ignores.xml
  def create
    @ignore = Analytics::Ignore.new(params[:analytics_ignore])

    respond_to do |format|
      if @ignore.save
        flash[:notice] = 'Analytics::Ignore was successfully created.'
        format.html { redirect_to(@ignore) }
      else
        format.html { render :action => "new" }
      end
    end
  end

  # PUT /ignores/1
  # PUT /ignores/1.xml
  def update
    @ignore = Analytics::Ignore.find(params[:id])

    respond_to do |format|
      if @ignore.update_attributes(params[:analytics_ignore])
        flash[:notice] = 'Analytics::Ignore was successfully updated.'
        format.html { redirect_to(@ignore) }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  # DELETE /ignores/1
  # DELETE /ignores/1.xml
  def destroy
    @ignore = Analytics::Ignore.find(params[:id])
    @ignore.destroy

    respond_to do |format|
      format.html { redirect_to(ignores_url) }
    end
  end
end

app/controllers/analytics/states_controller.rb
class Analytics::StatesController < Analytics::CommonController
  helper 'analytics/common'
  helper 'analytics/stats'
  include Analytics::ConversionsHelper

  def index
    respond_to do |format|
      format.html # show.html.erb
    end
  end

  def show
    @state = params[:id]
    date_range = grab_date_range
    time_period = params[:time_period].to_i.days
    end_state = @state.to_sym
    start_state = previous_state_from(end_state)
    stat = params[:stat].blank? ? :number : params[:stat].to_sym
    options = add_filter_options({:time_period=>time_period, :stat=>stat})

    respond_to do |format|
      format.html # show.html.erb
      format.json do
        render :json=>FunnelCake.engine.conversion_history(start_state, end_state, options).to_json and return
      end
      format.csv do
        send_data(FunnelCake.engine.conversion_history(start_state, end_state, options).values.first.to_csv,
              :type => 'text/csv; charset=utf-8; header=present',
              :filename => "#{@state}-#{params[:time_period]}day_details.csv") and return
      end
    end
  end

  def visitors
    @state = params[:id]
    date_range = grab_date_range
    time_period = params[:time_period].to_i.days
    end_state = @state.to_sym
    start_state = previous_state_from(end_state)
    stat = params[:stat].blank? ? :id : params[:stat].to_sym
    options = add_filter_options({:date_range=>date_range, :stat=>stat})

    visitors = state_graph_visitors(start_state, end_state, options)

    respond_to do |format|
      format.json do
        render :json=>visitors.to_json and return
      end
      format.csv do
        send_data(visitors.to_csv,
              :type => 'text/csv; charset=utf-8; header=present',
              :filename => "#{@state}-#{params[:time_period]}day_visitors.csv") and return
      end
    end
  end

end

app/controllers/analytics/stats_controller.rb
class Analytics::StatsController < Analytics::CommonController

  helper 'analytics/common'

  # def index
  #   respond_to do |format|
  #     format.html # show.html.erb
  #   end
  # end
  #

  def show
    @date_range = grab_date_range
    @stat = params[:id]

    @options = add_filter_options({:date_range=>@date_range})

    if @stat == 'entered_state_count'
      state = params[:state].to_sym
      prev_state = previous_state_from(state)
      @title = params[:title] or state.to_s.titleize
      stats = FunnelCake.engine.conversion_stats(prev_state, state, {:date_range=>@date_range, :attrition_period=>1.month}.merge(@options) )
      @value = stats[:end].to_i
      @stat_name = "#{@stat}-#{state}"
    else
      @title = params[:title] or 'Unknown'
      @value = 0
      @stat_name = ''
    end

    respond_to do |format|
      format.html
      format.js
    end
  end

  def index
    respond_to do |format|
      format.html
    end
  end

end

app/controllers/analytics/visitors_controller.rb
class Analytics::VisitorsController < Analytics::CommonController
  unloadable if RAILS_ENV=='development'

  # GET /visitors
  # GET /visitors.xml
  def index

    # Analytics::Visitor.recent.with_user.including_events.ordered
    @visitors_with_users = Analytics::Visitor.find(:all, :conditions=>{
      :created_at.gt=>1.month.ago.utc,
      :user_id.ne=>nil,
    }, :order=>'created_at DESC')

    # @visitors_without_users = Analytics::Visitor.recent.without_user.ordered
    @visitors_without_users = Analytics::Visitor.find(:all, :conditions=>{
      :created_at.gt=>1.month.ago.utc,
      :user_id=>nil,
    }, :order=>'created_at DESC')

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /visitors/1
  # GET /visitors/1.xml
  def show
    @visitor = Analytics::Visitor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  # GET /visitors/new
  # GET /visitors/new.xml
  def new
    @visitor = Analytics::Visitor.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /visitors/1/edit
  def edit
    @visitor = Analytics::Visitor.find(params[:id])
  end

  # POST /visitors
  # POST /visitors.xml
  def create
    @visitor = Analytics::Visitor.new(params[:visitor])

    respond_to do |format|
      if @visitor.save
        flash[:notice] = 'Analytics::Visitor was successfully created.'
        format.html { redirect_to(@visitor) }
      else
        format.html { render :action => "new" }
      end
    end
  end

  # PUT /visitors/1
  # PUT /visitors/1.xml
  def update
    @visitor = Analytics::Visitor.find(params[:id])

    respond_to do |format|
      if @visitor.update_attributes(params[:visitor])
        flash[:notice] = 'Analytics::Visitor was successfully updated.'
        format.html { redirect_to(@visitor) }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  # DELETE /visitors/1
  # DELETE /visitors/1.xml
  def destroy
    @visitor = Analytics::Visitor.find(params[:id])
    @visitor.destroy

    respond_to do |format|
      format.html { redirect_to(visitors_url) }
    end
  end
end

app/helpers/analytics/common_helper.rb
module Analytics::CommonHelper
  unloadable if RAILS_ENV=='development'

  include FunnelCake::StatePeriodHelpers

  def monthly_header
    "#{Date.today.beginning_of_month.to_s(:month_year)}, #{Date.today.end_of_month.day.to_i - Date.today.day.to_i} days remaining"
  end

  def generic_header_text(period)
    cp = current_period(period)
    "#{cp.begin.to_date.to_s(:short)} to #{(cp.begin + period).to_date.to_s(:short)}, #{period.to_i/1.day - day_within_current_period(period)} days remaining"
  end

  def biweekly_header
    generic_header_text(2.weeks)
  end

  def weekly_header
    generic_header_text(1.week)
  end

  def state_graph_visitors(start_state, end_state, opts)
    visitors = FunnelCake.engine.moved_to_state(end_state, opts).find.to_a
    FunnelCake::DataHash[*visitors.collect do |visitor|
      [visitor.id, FunnelCake::DataHash[visitor.to_funnelcake]]
    end.flatten]
  end

  def global_statistic_options_for_select(stat, options={})
    options = options.reverse_merge(:limit=>20)
    arr = FunnelCake.engine.global_statistic_results(stat, options).collect{|doc| [doc['_id'], doc['_id']]}
    options_for_select([['', '']] + arr, :selected=>'')
  end

end

app/helpers/analytics/conversions_helper.rb
module Analytics::ConversionsHelper
  unloadable if RAILS_ENV=='development'
end

app/helpers/analytics/dashboards_helper.rb
module Analytics::DashboardsHelper
  unloadable if RAILS_ENV=='development'
end

app/helpers/analytics/events_helper.rb
module Analytics::EventsHelper
  unloadable if RAILS_ENV=='development'

  def state_position(state)
    Analytics::Visitor.primary_states.index(state.to_sym) * 120
  end

end

app/helpers/analytics/states_helper.rb
module Analytics::StatesHelper
  unloadable if RAILS_ENV=='development'
end

app/helpers/analytics/stats_helper.rb
module Analytics::StatsHelper
  unloadable if RAILS_ENV=='development'

  def entered_state_count_stat(state, title)
    render '/analytics/stats/stat', :value=>'', :title=>title, :id=>"stat_entered_state_count-#{state}"
  end

end

app/views/analytics/events/_event.html.erb
  <tr id='event_<%=event.id%>' class='event'>
    <td><%= event.id %></td>
    <td><%= event.name %></td>
    <td><%= event.from %></td>
    <td><%= event.to %></td>
    <td><%= event.url.sub(/https?:\/\/[^\/]+/,'') unless event.url.nil? %></td>
    <td><%= event.visitor.user.email unless event.visitor.nil? or event.visitor.user.nil? %></td>
    <td><%= link_to event.visitor.id.to_s[0..5]+'...', analytics_visitor_path(event.visitor) unless event.visitor.nil? %></td>
    <td><%= event.visitor.ip unless event.visitor.nil? %></td>
    <td><%= event.created_at.to_s(:short) if event.created_at %>
	 <span id='datetime_<%=event.id%>' style="display: none;"><%=event.created_at%></span></td>
	 <td><%=link_to 'Show', analytics_event_path(event)%></td>
  </tr>

app/views/analytics/events/_funnel_stage.html.erb
<%- style='' if local_assigns[:style].nil? -%>
<%- date_range = 14.days.ago..0.days.ago if local_assigns[:date_range].nil? -%>
<%- top_label = true if local_assigns[:top_label].nil? -%>
<%- bottom_label = true if local_assigns[:bottom_label].nil? -%>
<%- next_state = next_state_from(state) if local_assigns[:next_state].nil? -%>
<%- id = "#{state}-#{next_state}" -%>
<%- stats = FunnelCake::Engine.conversion_stats(state, next_state, {:date_range=>date_range, :attrition_period=>1.month}) -%>
<div class='funnel_stage' id='funnel_stage_<%=id%>'>
	<div class='funnel_top_label funnel_stage_label' style='<%="display: none;" unless top_label%>'><%= state.to_s.titleize %></div>
	<div class='funnel_stage_container' id='funnel_stage_<%=id%>' style='<%=style%>'>
		<div class='funnel_rate_label'>
			<span class="count_stats start_count"><%= stats[:start_count] %></span><br/>
			<span class="rate_stats"><%= number_to_percentage(stats[:rate]*100.0, :precision=>1) %></span><br/>
			<span class="count_stats end_count"><%= stats[:end_count] %></span>
		</div>
	</div>
	<div class='funnel_bottom_label funnel_stage_label' style='<%="display: none;" unless bottom_label%>'><%= next_state.to_s.titleize %></div>
	<img class='spinner' id='funnel_stage_<%=id%>_spinner' src='/images/ajax-loader.gif' style='display: none;'/>
</div>

app/views/analytics/events/_state_graph.html.erb
<% style = '' if local_assigns[:style].nil? %>
<div class='state_graph_container' id='state_graph_<%= state %>_container' style='<%=style%>'>
	<div class='state_graph' id='state_graph_<%= state %>'></div>
	<img class='spinner state_graph_spinner' id='state_graph_<%= state %>_spinner' src='/images/ajax-loader.gif'>
</div>

app/views/analytics/events/_state_graph_update.html.erb
<script type="text/javascript">
var updateStateGraphs = function(period) {
	$$('.state_graph').each(function(e){
		var state_name = e.id.sub(/state_graph_/,'');
		$('state_graph_'+state_name+'_spinner').appear({duration: 0.5});
		new Ajax.Request('state_graph',
			{
				asynchronous:true,
				evalScripts:true,
				method:'get',
				parameters: {
					authenticity_token: '<%=escape_javascript(form_authenticity_token)%>',
					state: state_name,
					days: period
				}
			}
		);
	});
};
</script>

app/views/analytics/events/index.html.erb
<h3>Last <%=@events.size%> Conversion Funnel Events - <%=@events.first.created_at unless @events.empty?%> to <%=@events.last.created_at unless @events.empty?%></h3>
<h4><%=link_to 'View Funnel Conversions', analytics_conversions_path %></h4>
<table class='admin_table' id='events'>
  <tr class='admin_table_header' id='events_header'>
    <th>ID</th>
    <th>Event</th>
    <th>From</th>
    <th>To</th>
    <th>URL</th>
    <th>Email</th>
    <th>Visitor Key</th>
    <th>IP</th>
	 <th>Date</th>
	 <th></th>
  </tr>
	<%= render :partial => 'event', :collection=>@events %>
</table>
<!-- script type="text/javascript">
function timestampParam(){
	 var timestamp_id = $$('tr.event').first().childElements().first().innerHTML;
	 var timestamp = $('datetime_'+timestamp_id).innerHTML;
	 return encodeURI(timestamp);
}
</script -->
<%# = periodically_call_remote(:url=>{:controller=>'analytics/events', :action => 'index', :format=>:js},
										:frequency=>10, :method=>:get,
										:with => "'timestamp=' + timestampParam()") %>

app/views/analytics/events/show.html.erb
<table class='admin_vtable'>
	<tr><th>ID:</th><td><%= @event.id %></td></tr>
	<tr><th>Name:</th><td><%= @event.name %></td></tr>
	<tr><th>From:</th><td><%= @event.from %></td></tr>
	<tr><th>To:</th><td><%= @event.to %></td></tr>
	<tr><th>URL:</th><td><%= @event.url.sub(/https?:\/\/[^\/]+/,'') unless @event.url.nil? %></td></tr>
	<tr><th>Email:</th><td><%= @event.user.email unless @event.user.nil? %>
	<%= @event.visitor.user.email unless @event.visitor.nil? or @event.visitor.user.nil? %>
	</td></tr>
	<tr><th>Visitor Key:</th><td><%= @event.visitor.id.to_s[0..5]+'...' unless @event.visitor.nil? %></td></tr>
	<tr><th>IP:</th><td><%= @event.visitor.ip unless @event.visitor.nil? %></td></tr>
	<tr><th>Referer:</th><td><%= @event.referer %></td></tr>
	<tr><th>User-Agent:</th><td><%= @event.user_agent %></td></tr>

	<tr><th>Date:</th><td><%#= human_time(@event.created_at) %><%=@event.created_at.to_s(:short)%>
	<span id='datetime_<%=@event.id%>' style="display: none;"><%=@event.created_at%></span></td></tr>
</p>
<%= link_to 'Back', analytics_events_path %>