config/routes.rb
#
# Routes for FunnelCake rails engine
#
Rails.application.routes.draw do

  match 'analytics', :to => "Analytics::Dashboards#overview"

  namespace :analytics do
    resources :events
    
    resources :conversions do
      member do
        get :history
        get :visitors
      end
    end

    resources :states do
      member do
        get :visitors
      end
    end

    resources :ignores
    
    resources :visitors
    
    resources :stats
    
    resources :dashboards do
      collection do
        get :main
        get :cec
        get :diagram
        get :overview
        get :clear_cache
        get :customers
      end
    end
  end

end

app/models/analytics/event.rb
class Analytics::Event

  include Comparable
  def <=>(other)
    return 0 if created_at.nil? or other.created_at.nil?
    created_at <=> other.created_at
  end

end

app/models/analytics/ignore.rb
class Analytics::Ignore
end

app/models/analytics/visitor.rb
require 'funnel_cake/has_funnel/user_extensions'

module Analytics
  class Visitor
  include FunnelCake::HasFunnel::UserExtensions

  # Create a Analytics::Event, as a callback to a state_machine transition
  def log_transition(from, to, event, data, opts)
    update_statistics(data) if events.empty?  # if this is the first event, update the global statistics

    self.events << Analytics::Event.create({
      :from=>from.to_s, :to=>to.to_s,
      :url=>data[:url],
      :referer=>data[:referer],
      :user_agent=>data[:user_agent],
      :name=>event.to_s
    })
    self.save
  end

  # Utility method for logging funnel events from within application code
  # (This is probably how most funnel events will be triggered)
  # - First check if the event is legal... if not, log an error I guess!
  # - Second, send() the event method with the accompanying data
  def log_funnel_event(event, data={})
    unless self.valid_events.include?(event.to_sym)
      Rails.logger.info "#{self.class.to_s} couldn't log FunnelCake event: #{event} This event is not valid for state: #{self.current_state}, ip: #{self.ip}"
      return
    end
    self.send(event.to_s+"!", data)
  end

  end
end

app/controllers/analytics/common_controller.rb
class Analytics::CommonController < ApplicationController
  unloadable if RAILS_ENV=='development'

  before_filter :setup_funnel_cake_includes
  def setup_funnel_cake_includes
    @javascripts ||= []
    @stylesheets ||= []

    @javascripts.push 'excanvas'
    @javascripts.push 'funnelcake'
    @javascripts.push 'canviz'
    @javascripts.push 'path'
    @javascripts.push 'x11colors'
    @javascripts.push 'flotr.debug-0.2.0-alpha'
    @stylesheets.push 'funnel_cake'
  end

  helper 'analytics/common'
  include Analytics::CommonHelper

  private

  def add_filter_options(options)
    data = {}
    if params[:compare]
      compare = ActiveSupport::JSON.decode(params[:compare])
      data = {:compare=>compare.collect {|cur_filter_data| process_filter_data(cur_filter_data)}}
    end
    data = process_filter_data(ActiveSupport::JSON.decode(params[:filter_data])) if params[:filter_data]
    options.merge(data)
  end

  def process_filter_data(data)
    data = data.inject({}) do |h, (k, v)|
      v = convert_hash_values_to_regexes(v) if v.is_a?(Hash)
      h[k.to_sym] = v unless v.blank?
      h
    end
    data
  end

  def convert_hash_values_to_regexes(hash)
    hash.inject({}) do |h, (k,v)|
      h[k.to_sym] = v[/^\/.*\/$/].blank? ? v : /#{v[1..-2]}/ unless v.blank?
      h
    end
  end

  def grab_date_range
    if params[:time_period]
      return current_period(params[:time_period].to_i.days)
    elsif !params[:date_range_start].blank? and !params[:date_range_end].blank?
      return params[:date_range_start].to_date..params[:date_range_end].to_date
    end
    return 1.month.ago..0.days.ago
  end

end

app/controllers/analytics/conversions_controller.rb
class Analytics::ConversionsController < Analytics::CommonController
  include Analytics::ConversionsHelper

  before_filter :load_state_from_id, :only=>[:show, :history, :visitors]
  def load_state_from_id
    @start_state = params[:id].sub(/-.*/,'')
    @end_state = params[:id].sub(/[^-]*-/,'')
  end

  def index
    respond_to do |format|
      format.html # show.html.erb
    end
  end

  def compare
    respond_to do |format|
      format.html # show.html.erb
    end
  end

  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json do
        json = {}

        @date_range = grab_date_range
        @options = add_filter_options({:date_range=>@date_range, :attrition_period=>1.month})
        json[:stats] = FunnelCake.engine.conversion_stats(@start_state, @end_state, @options)

        if params[:show_previous_period]=='true'
          @previous_date_range = previous_date_range(@date_range, duration_of(@date_range)==30)
          @previous_options = add_filter_options({:date_range=>@previous_date_range, :attrition_period=>1.month})
          json[:previous_stats] = FunnelCake.engine.conversion_stats(@start_state, @end_state, @previous_options)
        end

        render :json=>json.to_json and return
      end
    end
  end

  def visitors
    @date_range = grab_date_range
    @options = add_filter_options({:date_range=>@date_range, :attrition_period=>1.month})
    respond_to do |format|
      format.html do
        render :partial=>'visitors',
                :locals=>{:start_state=>@start_state, :end_state=>@end_state, :options=>@options}
      end
    end
  end

  def history
    @time_period = params[:time_period].to_i.days
    @state = params[:id]
    stat = params[:stat].blank? ? :number : params[:stat].to_sym
    @options = add_filter_options({:time_period=>@time_period, :stat=>stat})
    respond_to do |format|
      format.json do
        render :json=>FunnelCake.engine.conversion_history(@start_state, @end_state, @options).to_json and return
      end
      format.csv do
        send_data(FunnelCake.engine.conversion_history(@start_state, @end_state, @options).values.first.to_csv,
              :type => 'text/csv; charset=utf-8; header=present',
              :filename => "#{@state}-#{params[:time_period]}day_history.csv") and return
      end
    end
  end

end

app/controllers/analytics/dashboards_controller.rb
class Analytics::DashboardsController < Analytics::CommonController

  helper 'analytics/stats'
  helper 'analytics/events'

  def diagram
    @date_range = grab_date_range
    @options = add_filter_options({:date_range=>@date_range, :attrition_period=>1.month})

    json = []
    Analytics::Visitor.event_table.each do |ev_name, ev|
      Analytics::Visitor.transition_table[ev_name].each do |trans|
        json << {
          :from => trans.from,
          :to => trans.to,
          :stats => FunnelCake.engine.move_stats(trans.from, trans.to, @options),
          :to_primary => Analytics::Visitor.states_table[trans.to].primary?
        }  unless Analytics::Visitor.states_table[trans.from].hidden? or Analytics::Visitor.states_table[trans.to].hidden?
      end
    end

    respond_to do |format|
      format.json { render :json=>json.to_json and return }
    end
  end

  def overview
  end

end

app/controllers/analytics/events_controller.rb
class Analytics::EventsController < Analytics::CommonController
  unloadable if RAILS_ENV=='development'

  helper 'analytics/stats'

  def index
    limit = params[:limit].nil? ? 25 : params[:limit]

    respond_to do |format|
      format.html do
        @events = Analytics::Visitor.all(:limit=>limit, :order=>'updated_at DESC')
        @events = @events.collect {|v| v.events}.flatten.delete_if {|e| e.nil? or e.created_at.nil?}.sort {|a,b| b.created_at <=> a.created_at }
      end
    end
  end

  # GET /events/1
  def show
    @event = Analytics::Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
    end
  end

end

app/controllers/analytics/ignores_controller.rb
class Analytics::IgnoresController < ApplicationController

  helper 'analytics/common'

  # GET /ignores
  # GET /ignores.xml
  def index
    @ignores = Analytics::Ignore.all

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /ignores/1
  # GET /ignores/1.xml
  def show
    @ignore = Analytics::Ignore.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  # GET /ignores/new
  # GET /ignores/new.xml
  def new
    @ignore = Analytics::Ignore.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /ignores/1/edit
  def edit
    @ignore = Analytics::Ignore.find(params[:id])
  end

  # POST /ignores
  # POST /ignores.xml
  def create
    @ignore = Analytics::Ignore.new(params[:analytics_ignore])

    respond_to do |format|
      if @ignore.save
        flash[:notice] = 'Analytics::Ignore was successfully created.'
        format.html { redirect_to(@ignore) }
      else
        format.html { render :action => "new" }
      end
    end
  end

  # PUT /ignores/1
  # PUT /ignores/1.xml
  def update
    @ignore = Analytics::Ignore.find(params[:id])

    respond_to do |format|
      if @ignore.update_attributes(params[:analytics_ignore])
        flash[:notice] = 'Analytics::Ignore was successfully updated.'
        format.html { redirect_to(@ignore) }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  # DELETE /ignores/1
  # DELETE /ignores/1.xml
  def destroy
    @ignore = Analytics::Ignore.find(params[:id])
    @ignore.destroy

    respond_to do |format|
      format.html { redirect_to(ignores_url) }
    end
  end
end

app/controllers/analytics/states_controller.rb
class Analytics::StatesController < Analytics::CommonController
  helper 'analytics/common'
  helper 'analytics/stats'
  include Analytics::ConversionsHelper

  def index
    respond_to do |format|
      format.html # show.html.erb
    end
  end

  def show
    @state = params[:id]
    date_range = grab_date_range
    time_period = params[:time_period].to_i.days
    end_state = @state.to_sym
    start_state = previous_state_from(end_state)
    stat = params[:stat].blank? ? :number : params[:stat].to_sym
    options = add_filter_options({:time_period=>time_period, :stat=>stat})

    respond_to do |format|
      format.html # show.html.erb
      format.json do
        render :json=>FunnelCake.engine.conversion_history(start_state, end_state, options).to_json and return
      end
      format.csv do
        send_data(FunnelCake.engine.conversion_history(start_state, end_state, options).values.first.to_csv,
              :type => 'text/csv; charset=utf-8; header=present',
              :filename => "#{@state}-#{params[:time_period]}day_details.csv") and return
      end
    end
  end

  def visitors
    @state = params[:id]
    date_range = grab_date_range
    time_period = params[:time_period].to_i.days
    end_state = @state.to_sym
    start_state = previous_state_from(end_state)
    stat = params[:stat].blank? ? :id : params[:stat].to_sym
    options = add_filter_options({:date_range=>date_range, :stat=>stat})

    visitors = state_graph_visitors(start_state, end_state, options)

    respond_to do |format|
      format.json do
        render :json=>visitors.to_json and return
      end
      format.csv do
        send_data(visitors.to_csv,
              :type => 'text/csv; charset=utf-8; header=present',
              :filename => "#{@state}-#{params[:time_period]}day_visitors.csv") and return
      end
    end
  end

end

app/controllers/analytics/stats_controller.rb
class Analytics::StatsController < Analytics::CommonController

  helper 'analytics/common'

  # def index
  #   respond_to do |format|
  #     format.html # show.html.erb
  #   end
  # end
  #

  def show
    @date_range = grab_date_range
    @stat = params[:id]

    @options = add_filter_options({:date_range=>@date_range})

    if @stat == 'entered_state_count'
      state = params[:state].to_sym
      prev_state = previous_state_from(state)
      @title = params[:title] or state.to_s.titleize
      stats = FunnelCake.engine.conversion_stats(prev_state, state, {:date_range=>@date_range, :attrition_period=>1.month}.merge(@options) )
      @value = stats[:end].to_i
      @stat_name = "#{@stat}-#{state}"
    else
      @title = params[:title] or 'Unknown'
      @value = 0
      @stat_name = ''
    end

    respond_to do |format|
      format.html
      format.js
    end
  end

  def index
    respond_to do |format|
      format.html
    end
  end

end

app/controllers/analytics/visitors_controller.rb
class Analytics::VisitorsController < Analytics::CommonController
  unloadable if RAILS_ENV=='development'

  # GET /visitors
  # GET /visitors.xml
  def index

    # Analytics::Visitor.recent.with_user.including_events.ordered
    @visitors_with_users = Analytics::Visitor.find(:all, :conditions=>{
      :created_at.gt=>1.month.ago.utc,
      :user_id.ne=>nil,
    }, :order=>'created_at DESC')

    # @visitors_without_users = Analytics::Visitor.recent.without_user.ordered
    @visitors_without_users = Analytics::Visitor.find(:all, :conditions=>{
      :created_at.gt=>1.month.ago.utc,
      :user_id=>nil,
    }, :order=>'created_at DESC')

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /visitors/1
  # GET /visitors/1.xml
  def show
    @visitor = Analytics::Visitor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  # GET /visitors/new
  # GET /visitors/new.xml
  def new
    @visitor = Analytics::Visitor.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /visitors/1/edit
  def edit
    @visitor = Analytics::Visitor.find(params[:id])
  end

  # POST /visitors
  # POST /visitors.xml
  def create
    @visitor = Analytics::Visitor.new(params[:visitor])

    respond_to do |format|
      if @visitor.save
        flash[:notice] = 'Analytics::Visitor was successfully created.'
        format.html { redirect_to(@visitor) }
      else
        format.html { render :action => "new" }
      end
    end
  end

  # PUT /visitors/1
  # PUT /visitors/1.xml
  def update
    @visitor = Analytics::Visitor.find(params[:id])

    respond_to do |format|
      if @visitor.update_attributes(params[:visitor])
        flash[:notice] = 'Analytics::Visitor was successfully updated.'
        format.html { redirect_to(@visitor) }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  # DELETE /visitors/1
  # DELETE /visitors/1.xml
  def destroy
    @visitor = Analytics::Visitor.find(params[:id])
    @visitor.destroy

    respond_to do |format|
      format.html { redirect_to(visitors_url) }
    end
  end
end

app/helpers/analytics/common_helper.rb
module Analytics::CommonHelper
  unloadable if RAILS_ENV=='development'

  include FunnelCake::StatePeriodHelpers

  def monthly_header
    "#{Date.today.beginning_of_month.to_s(:month_year)}, #{Date.today.end_of_month.day.to_i - Date.today.day.to_i} days remaining"
  end

  def generic_header_text(period)
    cp = current_period(period)
    "#{cp.begin.to_date.to_s(:short)} to #{(cp.begin + period).to_date.to_s(:short)}, #{period.to_i/1.day - day_within_current_period(period)} days remaining"
  end

  def biweekly_header
    generic_header_text(2.weeks)
  end

  def weekly_header
    generic_header_text(1.week)
  end

  def state_graph_visitors(start_state, end_state, opts)
    visitors = FunnelCake.engine.moved_to_state(end_state, opts).find.to_a
    FunnelCake::DataHash[*visitors.collect do |visitor|
      [visitor.id, FunnelCake::DataHash[visitor.to_funnelcake]]
    end.flatten]
  end

  def global_statistic_options_for_select(stat, options={})
    options = options.reverse_merge(:limit=>20)
    arr = FunnelCake.engine.global_statistic_results(stat, options).collect{|doc| [doc['_id'], doc['_id']]}
    options_for_select([['', '']] + arr, :selected=>'')
  end

end

app/helpers/analytics/conversions_helper.rb
module Analytics::ConversionsHelper
  unloadable if RAILS_ENV=='development'
end

app/helpers/analytics/dashboards_helper.rb
module Analytics::DashboardsHelper
  unloadable if RAILS_ENV=='development'
end

app/helpers/analytics/events_helper.rb
module Analytics::EventsHelper
  unloadable if RAILS_ENV=='development'

  def state_position(state)
    Analytics::Visitor.primary_states.index(state.to_sym) * 120
  end

end

app/helpers/analytics/states_helper.rb
module Analytics::StatesHelper
  unloadable if RAILS_ENV=='development'
end

app/helpers/analytics/stats_helper.rb
module Analytics::StatsHelper
  unloadable if RAILS_ENV=='development'

  def entered_state_count_stat(state, title)
    render '/analytics/stats/stat', :value=>'', :title=>title, :id=>"stat_entered_state_count-#{state}"
  end

end

app/views/analytics/conversions/_conversion.html.erb
<%- options = {} if local_assigns[:options].nil? -%>
<div class='funnel_conversion' id='funnel_conversion_<%=start_state%>-<%=end_state%>'>
</div>
<script type='text/javascript'>
	options = <%= options.to_json %>;
	if (options.clickHandler) { eval('tempFunc = '+options.clickHandler); options.clickHandler = tempFunc; }
	new ConversionFunnel($('funnel_conversion_<%=start_state%>-<%=end_state%>'), $H({
		startState: '<%=start_state%>',
		endState: '<%=end_state%>'
	}).merge(options).toObject());
</script>

app/views/analytics/conversions/_detail.html.erb
<div id='conversion_detail_<%=@state%>-<%=@next_state%>' class='conversion_detail'>
	<h2><%= "#{@state.to_s.titleize} to #{@next_state.to_s.titleize}" %></h2>
	<p><%= link_to "View this Conversion in Detail", analytics_conversion_path("#{@state}-#{@next_state}") %></p>
	<div class='visitors_notes_container' id='visitors_notes_container_<%=@state%>-<%=@next_state%>' style='clear: both;'>
		<%= render 'visitors', :state=>@state, :options=>@options %>
	</div><br />
	<%= render 'analytics/states/graph', :state=>@next_state, :time_period=>(@date_range.end.to_date - @date_range.begin.to_date).to_i.days %>
</div>

app/views/analytics/conversions/_graph.html.erb
<%- stat = 'number' if local_assigns[:stat].nil? -%>
<%- options = {} if local_assigns[:options].nil? -%>
<%-
	unless local_assigns[:width].nil? or local_assigns[:width].nil?
		style = "width: #{width}px; height: #{height}px;"
	else
		style = ''
	end
-%>
<div class='funnel_conversion_graph' id='funnel_conversion_graph_<%=start_state%>-<%=end_state%>_<%=stat%>' style="<%=style%>">
</div>
<script type='text/javascript'>
	new ConversionGraph($('funnel_conversion_graph_<%=start_state%>-<%=end_state%>_<%=stat%>'), $H({
		startState: '<%=start_state%>',
		endState: '<%=end_state%>',
		stat: '<%=stat%>',
		style: '<%=style%>'
	}).merge(<%= options.to_json %>).toObject());
</script>

app/views/analytics/conversions/compare.html.erb
<div class="section">
	<h1>Compare <span>Conversion Rates</span></h1>
	<div class="section full_width">
		<h2>Filter Controls</h2>
		<%= render :partial => 'analytics/common/daterange_label' %>
	</div>
	<div class="section full_width">
		<%= render 'analytics/common/filter_fields_input', :style=>'font-size: 12px', :compare=>'A' %>
		<%= render 'analytics/common/filter_fields_input', :style=>'font-size: 12px', :compare=>'B' %>
	</div>
	<%- Analytics::Visitor.primary_states[1..-1].each_with_index do |state, i| -%>
		<%- prev_state = previous_state_from(state) -%>
		<div class="section full_width">
			<div class="column span-6">
				<b><%=prev_state%> to <%=state%> Rate History</b>
				<%= render 'analytics/conversions/graph', :start_state=>prev_state, :end_state=>state, :stat=>:rate %>
			</div>
			<div class="column span-6">
				<b><%=prev_state%> to <%=state%> Absolute History</b>
				<%= render 'analytics/conversions/graph', :start_state=>prev_state, :end_state=>state %>
			</div>
		</div>
	<%- end -%>
</div>
<script type='text/javascript'>
<%= render 'analytics/common/filter_fields_update.js' %>
<%= render 'analytics/common/stats_update.js' %>

	var updateAnalyticsStats = function() {
		var period = $('date_period').value;
		var opts = {
			compare: [
				$H({
					first_event_with: { url: $('landing_page_matchA').value, referer: $('referer_matchA').value },
					has_event_with: { url: $('visited_page_matchA').value }
				}),
				$H({
					first_event_with: { url: $('landing_page_matchB').value, referer: $('referer_matchB').value },
					has_event_with: { url: $('visited_page_matchB').value }
				})
			].toJSON()
		};
		opts.time_period = periodDays(period);
		opts.period_start = periodStart(period);
		opts.period_end = periodEnd(period);

		setPeriodLabel(period);
		FunnelCakeWidget.update(opts);
	}

	FunnelCakeWidget.draw();
	updateAnalyticsStats();

</script>

app/views/analytics/conversions/index.html.erb
<div class="section">
	<h1>TransFS <span>Conversion Rates</span></h1>
	<div class="section full_width">
		<h2>Filter Controls</h2>
		<%= render :partial => 'analytics/common/daterange_label' %>
		<%= render :partial => 'analytics/common/filter_fields_input', :style=>'font-size: 14px' %>
	</div>
<%- Analytics::Visitor.primary_states[1..-1].each_with_index do |state, i| -%>
	<%- prev_state = previous_state_from(state) -%>
	<div class="section full_width">
		<div class="column span-3">
				<%= render 'analytics/conversions/conversion', :start_state=>prev_state, :end_state=>state,
						:options=>{:topLabel=>(i==0 ? prev_state.to_s.titleize : false), :bottomLabel=>link_to(state.to_s.titleize, analytics_conversion_path("#{prev_state}-#{state}"))} %>
		</div>
		<div class="column span-6">
			<b><%=prev_state%> to <%=state%> Rate History</b>
			<%= render 'analytics/conversions/graph', :start_state=>prev_state, :end_state=>state, :stat=>:rate %>
		</div>
		<div class="column span-6">
			<b><%=prev_state%> to <%=state%> Absolute History</b>
			<%= render 'analytics/conversions/graph', :start_state=>prev_state, :end_state=>state %>
		</div>
	</div>
<%- end -%>
</div>
<script type='text/javascript'>
<%= render 'analytics/common/filter_fields_update.js' %>
<%= render 'analytics/common/stats_update.js' %>

	var updateAnalyticsStats = function() {
		<%= render 'analytics/common/grab_filter_fields.js' %>
		setPeriodLabel(period)
		FunnelCakeWidget.update(opts);
	}

	FunnelCakeWidget.draw();
	updateAnalyticsStats();

</script>

app/views/analytics/conversions/show.html.erb
<div class="section span-12">
	<h1><span><%=@start_state.to_s.titleize%></span> to <span><%=@end_state.to_s.titleize%></span></h1>
	<div class="section span-12">
		<%= render :partial => 'analytics/common/filter_fields_input', :style=>'font-size: 14px' %>
		<%= render :partial => 'analytics/common/daterange_label' %>
	</div>
</div>
<div class="section span-12">
	<div class="column span-4">
		<%= render 'conversion', :start_state=>@start_state, :end_state=>@end_state %>
	</div>
	<div class='column span-8 last' id='state_chart_container'>
		<%= render 'analytics/conversions/graph', :start_state=>@start_state, :end_state=>@end_state %>
		<%= render 'analytics/conversions/graph', :start_state=>@start_state, :end_state=>@end_state, :stat=>:rate %>
	</div>
	<div class='column span-8 last' id='state_chart_container'>
		<h3>Visitors in End State: <%=@end_state%></h3>
		<%= render 'analytics/states/visitors_table', :state=>@end_state, :stats=>[:name, :email, :recent_event_date], :category=>'id' %>
	</div>
</div>
<script type="text/javascript">
<%= render 'analytics/common/filter_fields_update.js' %>
<%= render 'analytics/common/visitors_update.js' %>

	var updateAnalyticsStats = function() {
		<%= render 'analytics/common/grab_filter_fields.js' %>

		updateVisitorInfo(opts);
		setPeriodLabel(period)
		FunnelCakeWidget.update(opts);
	};

	FunnelCakeWidget.draw();
	updateAnalyticsStats();
</script>